server:
  port: 12012

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rem_db
    username: rem_admin
    password: rem_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: rem_schema

app:
  jwtSecret: WuCYQ8QBgmwgYS0sZpKxPSqcD8xNmB59/4t+/TPDVBUnLzS418tjy1jm+otbdPYmG4ABbAkwmAqkldbwVH7+yQ==
  jwtExpirationInMs: 3600000

logging:
  level:
    org: INFO