server:
  port: 8080

spring:
  datasource:
    url: <db-url>
    username: <db-username>
    password: <db-password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: <db-schema>

app:
  jwtSecret: <jwt-secret>
  jwtAccessExpirationInMs: <jwt-expiration-in-ms>
  jwtRefreshExpirationInMs: <jwt-expiration-in-ms>